/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fee;

/**
 *
 * @author kapil
 */
import EO.SchoolEO;
import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Date;
 
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.myapp.struts.Dataconnectivity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import pant.common.CommonFunctionality;
public class GenerateScrollPDF {
    private static String FILE = "D:\\kapil\\NetBean 7.2 Projects Code\\FMS_Pantnagar\\build\\web\\ScrollInPDF/B.Sc. Ag._2011_41388.pdf";
  private static Font boldFont1 = new Font(Font.FontFamily.TIMES_ROMAN, 12,Font.BOLD);
  private static Font greyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10,Font.NORMAL, BaseColor.GRAY);
  private static Font greyFont1 = new Font(Font.FontFamily.TIMES_ROMAN, 8,Font.NORMAL, BaseColor.GRAY);
  private static Font boldFont2 = new Font(Font.FontFamily.TIMES_ROMAN, 8,Font.BOLD);
  private static Font boldFont3 = new Font(Font.FontFamily.TIMES_ROMAN, 7,Font.BOLD);
  private static Font boldFont4 = new Font(Font.FontFamily.TIMES_ROMAN, 6,Font.BOLD);
  private static Font smallFont = new Font(Font.FontFamily.TIMES_ROMAN, 7);
  private static Font smallFont2 = new Font(Font.FontFamily.TIMES_ROMAN, 5);
  CommonFunctionality cFun=new CommonFunctionality();
//  Font.FontFamily.HELVETICA
  private static DecimalFormat df = new DecimalFormat("0.00");



  // iText allows to add metadata to the PDF which can be viewed in your Adobe
  // Reader
  // under File -> Properties
  public void addMetaData(Document document) {
    document.addTitle("GBPUAT");
    document.addSubject("Fee Scroll");
    document.addKeywords("Student ID , Programme");
    document.addAuthor("Kapil Saini");
    document.addCreator("Kapil Saini");
  }

  private void addTitlePage(Document document)
      throws DocumentException {
    Paragraph preface = new Paragraph();
    // We add one empty line
    addEmptyLine(preface, 1);
    // Lets write a big header
    preface.add(new Paragraph("Title of the document", boldFont1));

    addEmptyLine(preface, 1);
    // Will create: Report generated by: _name, _date
    preface.add(new Paragraph("Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
        boldFont3));
    addEmptyLine(preface, 3);
    preface.add(new Paragraph("This document describes something which is very important ",
        boldFont3));

    addEmptyLine(preface, 8);

    preface.add(new Paragraph("This document is a preliminary version and not subject to your license agreement or any other agreement with vogella.com ;-).",
        greyFont));

    document.add(preface);
    // Start a new page
    document.newPage();
  }

  public void addContent(Document document,ArrayList list,SchoolEO seo) throws DocumentException {
      String s[]={"Student Copy","University Copy (Student Section)"};
//      String sem[]={"I","II","III","IV","V","VI","VII","VIII","IX","X"};
      double tt=0.0;
      Converter cnvrt=new Converter();
        Round rnd=new Round();
        MyMethods mm=new MyMethods();
        StringBuffer sb=null;
      SchoolEO se=new SchoolEO();
      for(int j=0;j<list.size();j++){
//          String sm="";
          se=(SchoolEO)list.get(j);
//          int semest=Integer.parseInt(se.getSemester());
//          for(int l=0;l<sem.length;l++)
//          {
//              if(semest==(l+1))
//              {
//                  sm=sem[l+1];
//                  break;
//              }
//          }
      PdfPTable maintable = new PdfPTable(3);
      maintable.setWidths(new float[]{1f,1f,1f});
      maintable.setWidthPercentage(100);
      for(int i=0;i<s.length;i++){
          PdfPTable nested1 = new PdfPTable(1);
          PdfPCell cell=null;
          cell=new PdfPCell(new Phrase(s[i],boldFont4));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("G.B.Pant University Of Agriculture & Technology, Pantnagar",boldFont2));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell.setPaddingLeft(7f);
          cell.setPaddingRight(15f);
          nested1.addCell(cell);
          
       PdfPTable nested11 = new PdfPTable(2);   
       nested11.setWidthPercentage(100);
       nested11.setWidths(new int[]{2,3});
       cell=new PdfPCell(new Phrase("Punjab National Bank",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          cell.setPaddingRight(0f);
          nested11.addCell(cell);
          cell=new PdfPCell(new Phrase("Fee Scroll (Semester "+seo.getSession()+" -"+seo.getSemester()+")",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(5f);
          cell.setPaddingRight(5f);
          nested11.addCell(cell);
          
          cell=new PdfPCell(new Phrase(cFun.getStringFromString(se.getCollege()).toUpperCase(),boldFont2));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell.setColspan(2);
          cell.setPaddingLeft(7f);
          cell.setPaddingRight(15f);
          nested11.addCell(cell);
          
          PdfPTable nested11_1=new PdfPTable(2);
          nested11_1.setWidths(new int[]{1,2});
          cell=new PdfPCell(new Phrase("Student Id ",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested11_1.addCell(cell);
          cell=new PdfPCell(new Phrase(se.getStud_id(),boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingRight(15f);
          nested11_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Name ",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested11_1.addCell(cell);
          cell=new PdfPCell(new Phrase(se.getSname(),boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingRight(5f);
          nested11_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Programme ",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested11_1.addCell(cell);
          cell=new PdfPCell(new Phrase(se.getDegree(),boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingRight(15f);
          nested11_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Hostel ........",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingTop(3f);
          cell.setPaddingLeft(7f);
          nested11_1.addCell(cell);
          cell=new PdfPCell(new Phrase("Room No. .......",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
          cell.setPaddingTop(3f);
          cell.setPaddingRight(20f);
          nested11_1.addCell(cell);
          
          
          cell=new PdfPCell(nested11_1);
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setColspan(2);
          nested11.addCell(cell);
          
          cell=new PdfPCell(nested11);
          cell.setBorder(Rectangle.BOTTOM | Rectangle.TOP);
       nested1.addCell(cell);
       
       
       ArrayList heads=se.getDataArray2();
       HashMap hm=se.getDataMap();
 // Table      
       PdfPTable nested12 = new PdfPTable(2);          
       //nested12.setWidths(new float[]{0.5f,0.5f});
       nested12.setWidthPercentage(95);
       nested12.setHorizontalAlignment(Element.ALIGN_LEFT);
       for(int k=0;k<heads.size();k++)
       {
           // for heads fee
           cell=new PdfPCell(new Phrase(heads.get(k).toString(),smallFont2));
           cell.setBorder(PdfPCell.NO_BORDER);
           cell.setHorizontalAlignment(Element.ALIGN_LEFT);
           cell.setPaddingLeft(7f);
           cell.setPaddingTop(0f);
           cell.setPaddingBottom(0f);
           nested12.addCell(cell);
           try{
            cell=new PdfPCell(new Phrase(df.format(Double.parseDouble(hm.get(heads.get(k)).toString())),smallFont2));
           }catch(Exception eee){
              cell=new PdfPCell(new Phrase(df.format(new Double(0)),smallFont2)); 
           }
           cell.setBorder(PdfPCell.NO_BORDER);
           cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
           cell.setPaddingTop(0f);
       cell.setPaddingBottom(0f);
           nested12.addCell(cell);
       }
       
       // for fine
       double fine=se.getFine();
       cell=new PdfPCell(new Phrase("FINE",smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       cell.setPaddingTop(0f);
       cell.setPaddingBottom(0f);
       nested12.addCell(cell);
           
       cell=new PdfPCell(new Phrase(df.format(fine),smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
       cell.setPaddingTop(0f);
       cell.setPaddingBottom(0f);
       nested12.addCell(cell);
       
       // for programme fee
       cell=new PdfPCell(new Phrase("PROGRAMME FEE",smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       cell.setPaddingTop(0f);
       cell.setPaddingBottom(0f);
       nested12.addCell(cell);
           
       cell=new PdfPCell(new Phrase(df.format(se.getPamount()),smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
       cell.setPaddingTop(0f);
       cell.setPaddingBottom(0f);
       nested12.addCell(cell);
       
       // for Extra fee
       cell=new PdfPCell(new Phrase("EXTRA",smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       cell.setPaddingTop(0f);
       cell.setPaddingBottom(0f);
       nested12.addCell(cell);
           
       cell=new PdfPCell(new Phrase(df.format(se.getEamount()),smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
       cell.setPaddingTop(0f);
       cell.setPaddingBottom(0f);
       nested12.addCell(cell);
       
       
       cell=new PdfPCell(new Paragraph(""));
       cell.addElement(nested12);
       cell.setBorder(Rectangle.BOTTOM | Rectangle.TOP);
       nested1.addCell(cell);
 
// Table 
       tt=0.0;
       tt=se.getFeeTotal()+fine+se.getPamount();
       tt=(double)Math.round(tt);
       PdfPTable nested13 = new PdfPTable(2);   
       nested13.setWidths(new int[]{1,2});
       nested13.setWidthPercentage(95);
       nested13.setHorizontalAlignment(Element.ALIGN_LEFT);
   // Total    
       cell=new PdfPCell(new Phrase("Total Fee Rs.",boldFont3));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setVerticalAlignment(Element.ALIGN_CENTER);
       cell.setPaddingLeft(7f);
//       cell.setMinimumHeight(20f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Phrase(df.format(tt),boldFont3));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
       cell.setVerticalAlignment(Element.ALIGN_CENTER);
//       cell.setMinimumHeight(20f);
       nested13.addCell(cell);
       
   //Bank Transaction
       cell=new PdfPCell(new Phrase("",greyFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell.setMinimumHeight(20f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Phrase("BANK SEAL",greyFont));
       cell.setPadding(10);
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setMinimumHeight(20f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Bank Transaction ID",boldFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setMinimumHeight(20f);
       cell.setPaddingLeft(7f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Phrase("",smallFont));
//       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setMinimumHeight(20f);
       cell.setPaddingRight(13f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Date",boldFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setMinimumHeight(10f);
       cell.setPaddingLeft(7f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Phrase("",smallFont));
//       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setMinimumHeight(20f);
       cell.setPaddingRight(13f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Cashier/Officer Signature & Bank Stamp",boldFont3));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell.setMinimumHeight(40f);
       cell.setColspan(2);
       cell.setPaddingLeft(7f);
       cell.setPaddingRight(13f);
       nested13.addCell(cell);
       
       cell=new PdfPCell(new Paragraph(""));
       cell.addElement(nested13);
       cell.setBorder(Rectangle.BOTTOM | Rectangle.TOP);
       nested1.addCell(cell);
       
//Table for Comptroller
       PdfPTable nested14 = new PdfPTable(1);   
       nested12.setWidths(new int[]{1,1});
       
       cell=new PdfPCell(new Phrase("Office Of The Comptroller",boldFont1));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell.setMinimumHeight(20f);
       cell.setPaddingLeft(7f);
       cell.setPaddingRight(13f);
       nested14.addCell(cell);
       
       cell=new PdfPCell(new Phrase("No Dues outstanding. All fees and food charges paid.",boldFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setMinimumHeight(35f);
       cell.setPaddingLeft(7f);
       cell.setPaddingRight(13f);
       nested14.addCell(cell);
       
       cell=new PdfPCell(new Phrase("For Comptroller",boldFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
       cell.setPaddingRight(20);
       cell.setMinimumHeight(20f);
       nested14.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Date",boldFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(5);
       cell.setMinimumHeight(20f);
       nested14.addCell(cell);
       
       cell=new PdfPCell(new Phrase("No-Dues Stamp",greyFont1));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell.setMinimumHeight(20f);
       nested14.addCell(cell);
       
       cell=new PdfPCell(nested14);
       cell.setBorder(Rectangle.BOTTOM | Rectangle.TOP);
       nested1.addCell(cell);
          
    maintable.addCell(nested1);
   
    }
      PdfPTable nested2 = new PdfPTable(2);
      nested2.setWidthPercentage(95);
      nested2.setWidths(new int[]{2,3});
      PdfPCell cell=null;
          cell=new PdfPCell(new Phrase("Bank Copy",boldFont4));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setColspan(2);
          cell.setPaddingLeft(7f);
          nested2.addCell(cell);
          
          cell=new PdfPCell(new Phrase("G.B.Pant University Of Agriculture & Technology, Pantnagar",boldFont2));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell.setColspan(2);
          cell.setPaddingLeft(7f);
          //cell.setPaddingRight(13f);
          nested2.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Punjab National Bank",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested2.addCell(cell);
          cell=new PdfPCell(new Phrase("Fee Scroll (Semester "+seo.getSession()+" -"+seo.getSemester()+")",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
          //cell.setPaddingRight(10f);
          nested2.addCell(cell);
          
             
       PdfPTable nested21 = new PdfPTable(2);   
       nested21.setWidthPercentage(100);
       cell=new PdfPCell(new Phrase("Through Pay Fee Menu",smallFont2));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setColspan(2);
          cell.setPaddingLeft(7f);
          nested21.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Pay Fee Menu ID: GBPUA",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Course ID: "+se.getCourse_id(),boldFont4));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
          //cell.setPaddingRight(15f);
          nested21.addCell(cell);
          
          PdfPTable nested21_1=new PdfPTable(2);
          nested21_1.setWidths(new int[]{1,2});
          cell=new PdfPCell(new Phrase("Student Id ",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21_1.addCell(cell);
          cell=new PdfPCell(new Phrase(se.getStud_id(),boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Name ",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21_1.addCell(cell);
          cell=new PdfPCell(new Phrase(se.getSname(),boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Programme ",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21_1.addCell(cell);
          cell=new PdfPCell(new Phrase(se.getDegree(),boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Total Fee",boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21_1.addCell(cell);
          cell=new PdfPCell(new Phrase(df.format(tt),boldFont3));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21_1.addCell(cell);
          
          sb=new StringBuffer("(");
          sb=sb.append(cnvrt.convertNumber(rnd.real(mm.precesion(Double.toString(tt),2))).toUpperCase());
          if(!rnd.fraction(mm.precesion(Double.toString(tt),2).toUpperCase()).equals("0")){
              sb=sb.append(" & ");
              sb=sb.append(cnvrt.convertNumber(rnd.fraction(mm.precesion(Double.toString(tt),2))).toUpperCase());
              sb=sb.append(" PAISE");
          }
          sb=sb.append(" ONLY)");
          cell=new PdfPCell(new Phrase(sb.toString(),smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
          cell.setColspan(2);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Signature of Depositer",smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
          cell.setMinimumHeight(30);
          cell.setColspan(2);
          cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Name",smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21_1.addCell(cell);
          cell=new PdfPCell(new Phrase("...............................................",smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Address",smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21_1.addCell(cell);
          cell=new PdfPCell(new Phrase("...............................................",smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(new Phrase("Phone/Mobile No",smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          cell.setPaddingLeft(7f);
          nested21_1.addCell(cell);
          cell=new PdfPCell(new Phrase("...............................................",smallFont));
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21_1.addCell(cell);
          
          cell=new PdfPCell(nested21_1);
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setColspan(2);
          cell.setHorizontalAlignment(Element.ALIGN_LEFT);
          nested21.addCell(cell);
          
          cell=new PdfPCell(new Paragraph(""));
          cell.addElement(nested21);
          cell.setColspan(2);
//          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setBorder(Rectangle.TOP);
       nested2.addCell(cell);
       
// Table Bank Use
       PdfPTable nested22 = new PdfPTable(2);   
       nested22.setWidthPercentage(100);
       nested22.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell=new PdfPCell(new Phrase("Bank Use",boldFont1));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setColspan(2);
       cell.setBackgroundColor(BaseColor.GRAY);
       cell.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell.setPaddingLeft(7f);
       nested22.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Bank Transaction ID",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       nested22.addCell(cell);
       cell=new PdfPCell(new Phrase(".................................................",smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       nested22.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Date",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       nested22.addCell(cell);
       cell=new PdfPCell(new Phrase(".................................................",smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       nested22.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Cashier/Officer Signature & Bank Stamp",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setColspan(2);
       cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
       cell.setPaddingRight(5);
       cell.setMinimumHeight(70);
       nested22.addCell(cell);
       
          cell=new PdfPCell(new Paragraph(""));
          cell.addElement(nested22);
          cell.setBorder(PdfPCell.NO_BORDER);
          cell.setColspan(2);
          cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
//          cell.setBorder(Rectangle.BOTTOM | Rectangle.TOP);
       nested2.addCell(cell);
       
// Table Fee Details
       PdfPTable nested23 = new PdfPTable(2);   
       nested23.setWidthPercentage(100);
       nested23.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell=new PdfPCell(new Phrase("Details of Fee",boldFont3));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setColspan(2);
       cell.setBackgroundColor(BaseColor.GRAY);
       cell.setHorizontalAlignment(Element.ALIGN_CENTER);
       cell.setPaddingLeft(7f);
       nested23.addCell(cell);
       
       cell=new PdfPCell(new Phrase("DD/Cheque No .....................",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       nested23.addCell(cell);
       cell=new PdfPCell(new Phrase("Amount ........................",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       nested23.addCell(cell);
       
       String rs[]={"1000x","500x","100x","50x","20x","10x","5x","2x","1x"};
       for(int k=0;k<rs.length;k++){
       cell=new PdfPCell(new Phrase(rs[k]+"............ = ",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       nested23.addCell(cell);
       cell=new PdfPCell(new Phrase(".................................................",smallFont2));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       nested23.addCell(cell);
      }
       
       cell=new PdfPCell(new Phrase("Total Amount Rs.",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       nested23.addCell(cell);
       cell=new PdfPCell(new Phrase("............................................",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       nested23.addCell(cell);
       
       cell=new PdfPCell(new Phrase("Amount in words",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       cell.setPaddingLeft(7f);
       nested23.addCell(cell);
       cell=new PdfPCell(new Phrase("............................................",smallFont));
       cell.setBorder(PdfPCell.NO_BORDER);
       cell.setHorizontalAlignment(Element.ALIGN_LEFT);
       nested23.addCell(cell);
       
       
          cell=new PdfPCell(new Paragraph(""));
          cell.addElement(nested23);
          cell.setColspan(2);
          cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
          cell.setBorder(Rectangle.BOTTOM);
       nested2.addCell(cell);
       
      cell=new PdfPCell(new Paragraph(""));
      cell.addElement(nested2);
      maintable.addCell(cell);
      
      document.add(maintable);
      document.newPage();
      }
  }

  private static void createTable(Section subCatPart)
      throws BadElementException {
    PdfPTable table = new PdfPTable(3);

    // t.setBorderColor(BaseColor.GRAY);
    // t.setPadding(4);
    // t.setSpacing(4);
    // t.setBorderWidth(1);

    PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("Table Header 2"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("Table Header 3"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(c1);
    table.setHeaderRows(1);

    table.addCell("1.0");
    table.addCell("1.1");
    table.addCell("1.2");
    table.addCell("2.1");
    table.addCell("2.2");
    table.addCell("2.3");

    subCatPart.add(table);

  }

  private static void createList(Section subCatPart) {
    List list = new List(true, false, 10);
    list.add(new ListItem("First point"));
    list.add(new ListItem("Second point"));
    list.add(new ListItem("Third point"));
    subCatPart.add(list);
  }

  private static void addEmptyLine(Paragraph paragraph, int number) {
    for (int i = 0; i < number; i++) {
      paragraph.add(new Paragraph(" "));
    }
  }
  
    public static void main(String[] args) {
    try {
        FeeMath fm=new FeeMath();
        SchoolEO seo=new SchoolEO();
GenerateScrollPDF gsp=new GenerateScrollPDF();
    seo.setDegree("B.Sc. Ag.");
    seo.setBatch("2013");
    seo.setSession("2014-2015");
    seo.setSession_sem("I");
//ArrayList list=fm.genFeeScrollProgwise(seo);
      
      
      Connection con=null;
       
  try{
  Dataconnectivity dc=new Dataconnectivity();
  con=(Connection)dc.Dataconnect();
  }catch(Exception e){}
  
  ArrayList ar=new ArrayList();
       ArrayList ar1=new ArrayList();
       String qr6="select distinct heads, heads_cat,field_name from feeheads order by heads_cat desc";

     PreparedStatement psmt2=con.prepareStatement(qr6);
     ResultSet rs2=psmt2.executeQuery(); 
      while(rs2.next()){
      ar.add(rs2.getString("heads"));
      ar1.add(rs2.getString("field_name"));
      }     
      HashMap hm=new HashMap();
        ArrayList staffheads=new ArrayList();
        
       SchoolEO seo1=new SchoolEO();
       seo1.setStud_id("41388");
       seo1=fm.getStudentDetails(seo1);
       seo1.setBatch("2011");
       
//       System.out.println(seo1);
       qr6="select * from stud_fee_detail_excel where stud_id=? and batch=?";
       PreparedStatement psmt5=con.prepareStatement(qr6);
      psmt5.setString(1, seo1.getStud_id());
      psmt5.setString(2, seo1.getBatch());
      ResultSet rs5=psmt5.executeQuery();
      if(rs5.next())
      {
          seo1.setPamount(rs5.getDouble("self_finance_fee"));
          seo1.setFee(rs5.getDouble("institu_fee"));
          seo1.setEamount(rs5.getDouble("extra"));
          seo1.setFeeTotal(rs5.getDouble("total_amount")-seo1.getPamount());
          int sz=ar1.size();
          for(int j=0;j<sz;j++)
          {
              hm.put(ar.get(j), rs5.getString(ar1.get(j).toString()));
          }
      }   
      


      seo1.setDataArray2(ar);
//      System.out.println("helloooo "+seo1.getDataArray2().size());
//      System.out.println(seo1.getDataArray2());
      seo1.setDataMap(hm);
//      System.out.println(seo1.getDataMap());
      
      ArrayList stud_datalist=new ArrayList();
      stud_datalist.add(seo1);
      Document document = new Document();
      PdfWriter.getInstance(document, new FileOutputStream(FILE));
      document.open();
      gsp.addMetaData(document);
//      addTitlePage(document);
      gsp.addContent(document,stud_datalist,seo);
      document.close();
      
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
